### ISSUE TITLE
Sometimes the layout editing function does not work.

### ISSUE THREAD

**Issue by umkasanki** [angell-co/Spoon#59] opened 2019-04-18 13:14 UTC
Screen video recording:  https://drive.google.com/file/d/1HSR64bJlLD2aNND7f1yyY5IvJr-6csnF/view?usp=sharing
log: [web.zip](https://github.com/angell-co/Spoon/files/3094517/web.zip)

Spoon | 3.3.6
PHP version | 7.2.10
WINNT 6.1
MySQL 5.7.24
Craft Solo 3.1.23

**Comment by joshangell** [comment] 2019-04-25 12:02
Hi @umkasanki, I think this is actually the same root cause as #57 which I’ve just pushed a fix to develop for. Give it a whirl.

**Closed** 2019-04-25 12:09 UTC
