### ISSUE TITLE
Unable to update to the latest version 3.4.1

### ISSUE THREAD

**Issue by baronetto** [angell-co/Spoon#75] opened 2019-12-05 02:25 UTC
When I try to install via the CLI or the CP I get the following error:

```
Problem 1
- Installation request for angellco/spoon 3.4.1 -> satisfiable by angellco/spoon[3.4.1].
- angellco/spoon 3.4.1 requires php >=7.1.0 -> your PHP version (7.3.8-1+ubuntu16.04.1+deb.sury.org+1) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
```

**Comment by joshangell** [comment] 2019-12-05 22:11
Thanks @baronetto, closing as duplicate of #74

**Closed by joshangell** 2019-12-05 22:11 UTC
Labels: duplicate

**Comment by joshangell** [comment] 2019-12-09 21:22
Hi @baronetto this has been fixed now in the latest release.

**Comment by baronetto** [comment] 2019-12-09 22:07
@joshangell Thank you for the update!
