### ISSUE TITLE
Broken Tabs

### ISSUE THREAD

**Issue by richhayler** [angell-co/Spoon#39] opened 2018-12-17 19:45 UTC
It appears intermittent but in my experience Spoon's tabbed interface repeatedly breaks and reverts to the default view (all fields within a matrix displayed within a single pane). This seems to be happening more often after the initial entry save and then returning to the entry to edit the matrix data.

I am using a CodeMirror, ColorIt and Asset field within my matrix and have a tab for each.

CraftCMS 3.0.35
Plugins: CodeMirror, ColorIt

**Comment by joshangell** [comment] 2018-12-18 16:01
Hi Rich, I’ll try and have a look into for you this week - are you getting any errors in the console do you know?

**Comment by joshangell** [comment] 2019-01-10 13:21
Hey Rich, I’m not able to reproduce this at the moment, but I am working on a full refactoring of the JS and how I attach to Matrix fields. I’ll close this for now, follow #9 for updates on the refactoring and then if its still a problem when that stuff is live we can revisit it.

**Closed by joshangell** 2019-01-10 13:21 UTC
Labels: bug
